# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]

# A basic redirect rule
[[redirects]]
  from = "/posts/2021/my_firstblood_methodology/"
  to = "https://www.bugbountyhunter.com/articles/?on=firstbloodhackers"
  status = 301
  force = false
